### PR TITLE
Carolyn's Work

### PR DESCRIPTION
**Pull request by smashwilson**
Carolyn's Docker Swarm slides

### CODE REVIEW

**Comment by etoews** [comment]
@carolynvs can just go ahead and push directly to master.

**Comment by rgbkrk** [comment]
Just ran through this, it's great!

**Comment by rgbkrk** [comment]
We do have the original for the carina diagram by the way, in case you want it to match the theme. I made it on draw.io.

**Comment by carolynvs** [comment]
Sure, can you send it to me?

**Comment by rgbkrk** [comment]
Done, shared it on draw.io. Let me know if you don't get an email from them soon.

**Pull request closed without merging**
